service: southchina-rss

provider:
  name: aws
  runtime: nodejs16.x

functions:
  check:
    handler: index.check
    description: generate RSS feed from the SCMP trail running news page
    events:
      - http:
          path: rss
          method: get
          cors: true
          integration: lambda
          response:
            headers:
              Content-Type: "'text/xml'"
            template: $input.path('$')
